image:
  file: .gitpod.Dockerfile

tasks:
  - name: spring-petclinic-angular
    before: cd ../spring-petclinic-angular
    init: npm install && npm run build
    command: |
      npm run start
  - name: spring-petclinic-reactive
    init: mvn package
    command: . setup.sh && mvn spring-boot:run

ports:
  - port: 4200
    onOpen: open-preview  
  - port: 9966
    onOpen: open-preview
  - port: 9967
    onOpen: ignore

github:
  prebuilds:
    master: false
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
    addLabel: false

