image:
  file: .gitpod.Dockerfile

tasks:
  - name: spring-petclinic-angular
    before: cd /workspace && git clone https://github.com/spring-petclinic/spring-petclinic-angular.git && cd /workspace/spring-petclinic-angular
    init: npm install && npm run build
    command: |
      npm run start
  - name: spring-petclinic-reactive
    init: mvn package
    command: . setup.sh && mvn package && java -jar target/spring-petclinic-reactive-1.0.0-SNAPSHOT.jar 

ports:
  - port: 4200
    onOpen: open-preview  
  - port: 9966
    onOpen: open-preview
  - port: 9967
    onOpen: ignore

github:
  prebuilds:
    master: false
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
    addLabel: false

