# docker exec -it `docker ps | grep cassandra:3.11.7 | cut -b 1-12` cqlsh -e "create keyspace petclinic WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 };"
# docker exec -it `docker ps | grep cassandra:3.11.7 | cut -b 1-12` cqlsh -e "describe keyspaces"
version: "3.8"
services:

  cassandra:
    image: cassandra:3.11.7
    ports:
      - 7000:7000
      - 9042:9042
    ulimits:
      memlock: -1

  spring-petclinic-reactive:
    image: com.springframework/spring-petclinic-reactive:1.0
    build:
      context: .
      #dockerfile: Dockerfile
      dockerfile: Dockerfilefast
      labels:
        com.springframework.samples.description: "pet Clinic"
    ports:
      - 8081:8081
    depends_on:
      - cassandra